const ADJECTIVES = [
    'Salty',
    'Magnificent',
    'Shiny',
    'Incomprehensible',
    'Effervescent',
    'Sparkly',
    'Scrumtrulescent',
    'Wonky',
    'Checkered',
    'Spindly',
    'Lorge',
    'Fluffy',
    'Ragin',
    'Partyrific',
    'Spacey',
    'Silvery',
    'Checkered',
    'Spikey',
    'Optional',
    'Wavy',
    'Poofy',
    'Puffy',
    'Fantastic',
    'Exceptional',
    'Swedish',
    'Extraordinary',
    'Sassy',
    'Peppy',
    'Frosty',
    'Donut-fueled',
    'Party',
    'Linoleum',
    'Direct',
    'Sensational',
    'Crazy',
    'Radical',
    'Blue',
    'Ryan-tastic',
    'Metaphysical',
    'Checkered',
    'Paisley',
    'Glittering',
    'Boisterous',
    'Speckled',
];

const NOUNS = [
    'Darkness',
    'Giraffe',
    'Table',
    'Dancer',
    'Coffee Pot',
    'Rainbow',
    'Armadillo',
    'Sasquatch',
    'Pizza',
    'Bee',
    'Rebel',
    'Instigator',
    'Duck',
    'Palm Tree',
    'Gemstone',
    'Cement Block',
    'Sunset',
    'Panda',
    'Dance Floor',
    'Truck',
    'Knife',
    'Party',
    'Lemons',
    'Brick House',
    'Key Lime',
    'Flamingo',
    'Badger',
    'Mongoose',
    'Otter',
    'Dinosaur',
    'Disco',
    'Existential Dread',
    'Jorts',
    'Pop-Tart',
    'Parental Disappointment',
    'Juicer',
    'Microphone',
    'Ryan',
    'Disco',
    'Rave',
    'Crow',
    'Rollerblades',
    'Dani Duck',
];

module.exports = {
    ADJECTIVES,
    NOUNS
}