DROP TABLE IF EXISTS users CASCADE; 
DROP TABLE IF EXISTS songs CASCADE;

CREATE TABLE users (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL
);
CREATE TABLE songs (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    vid_id TEXT NOT NULL,
    thumbnail TEXT NOT NULL,
    channel_name TEXT NOT NULL,
    channel_id TEXT NOT NUll
);